// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210055417_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.Models.DashboardCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Approved_Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("Generated_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Plagiarism_Count")
                        .HasColumnType("int");

                    b.Property<int>("Reject_Count")
                        .HasColumnType("int");

                    b.Property<int>("Semester_Id")
                        .HasColumnType("int");

                    b.Property<int>("Submitted_Count")
                        .HasColumnType("int");

                    b.Property<int>("Total_Students")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Semester_Id");

                    b.ToTable("DashboardCaches");
                });

            modelBuilder.Entity("BusinessObject.Models.ReviewLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("New_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Original_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Reviewer_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Submission_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Reviewer_Id");

                    b.HasIndex("Submission_Id");

                    b.ToTable("ReviewLogs");
                });

            modelBuilder.Entity("BusinessObject.Models.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Semesters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            End_Date = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Start_Date = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Term = "Fall 2025",
                            Year = 2025
                        },
                        new
                        {
                            Id = 2,
                            End_Date = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Start_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Term = "Spring 2026",
                            Year = 2026
                        },
                        new
                        {
                            Id = 3,
                            End_Date = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Start_Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Term = "Summer 2026",
                            Year = 2026
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.StudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Created_By")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Topic_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Created_By");

                    b.HasIndex("Topic_Id");

                    b.ToTable("StudentGroups");
                });

            modelBuilder.Entity("BusinessObject.Models.StudentGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Group_Id")
                        .HasColumnType("int");

                    b.Property<bool>("Is_Leader")
                        .HasColumnType("bit");

                    b.Property<Guid>("Student_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Group_Id");

                    b.HasIndex("Student_Id");

                    b.ToTable("StudentGroupMembers");
                });

            modelBuilder.Entity("BusinessObject.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Group_Id")
                        .HasColumnType("int");

                    b.Property<bool>("Plagiarism_Flag")
                        .HasColumnType("bit");

                    b.Property<float>("Plagiarism_Score")
                        .HasColumnType("real");

                    b.Property<string>("Reject_Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Reviewed_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Semester_Id")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Submitted_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Topic_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Group_Id");

                    b.HasIndex("Semester_Id");

                    b.HasIndex("Topic_Id");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("BusinessObject.Models.SubmissionFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("File_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("File_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firebase_Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Submission_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Uploaded_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Submission_Id");

                    b.ToTable("SubmissionFiles");
                });

            modelBuilder.Entity("BusinessObject.Models.SuspensionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved_By_Gpec")
                        .HasColumnType("bit");

                    b.Property<bool>("Approved_By_Sdc")
                        .HasColumnType("bit");

                    b.Property<bool>("Detected_By_Ai")
                        .HasColumnType("bit");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Student_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Submission_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Student_Id");

                    b.HasIndex("Submission_Id");

                    b.ToTable("SuspensionRecords");
                });

            modelBuilder.Entity("BusinessObject.Models.ThesisModeration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Academic_Rigor_Pass")
                        .HasColumnType("bit");

                    b.Property<bool>("Citation_Quality_Pass")
                        .HasColumnType("bit");

                    b.Property<bool>("Completeness_Pass")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ethical_Compliance_Pass")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Approved")
                        .HasColumnType("bit");

                    b.Property<bool>("Originality_Pass")
                        .HasColumnType("bit");

                    b.Property<bool>("Plagiarism_Pass")
                        .HasColumnType("bit");

                    b.Property<float>("Plagiarism_Score")
                        .HasColumnType("real");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Research_Relevance_Pass")
                        .HasColumnType("bit");

                    b.Property<int>("Submission_Id")
                        .HasColumnType("int");

                    b.Property<string>("Violations_Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Writing_Quality_Pass")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Submission_Id")
                        .IsUnique();

                    b.ToTable("ThesisModerations");
                });

            modelBuilder.Entity("BusinessObject.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Created_By")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deadline_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Group_Required")
                        .HasColumnType("bit");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Semester_Id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Created_By");

                    b.HasIndex("Semester_Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_By = new Guid("aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Deadline_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đo lường vốn từ vựng phái sinh của sinh viên học tiếng Anh như một ngoại ngữ bằng bài kiểm tra không có ngữ cảnh",
                            Is_Group_Required = false,
                            Major = "Ngôn Ngữ Anh",
                            Semester_Id = 1,
                            Title = "Measuring Vietnamese EFL learners’ productive derivative knowledge in a decontextualized test format"
                        },
                        new
                        {
                            Id = 2,
                            Created_By = new Guid("aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Deadline_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gọi ngẫu nhiên, làm việc nhóm và kiểm tra trắc nghiệm trực tuyến trong vai trò dự báo lo âu trong lớp học tiếng Anh dự bị (ENT) tại Trường Đại học FPT",
                            Is_Group_Required = false,
                            Major = "Ngôn Ngữ Anh",
                            Semester_Id = 1,
                            Title = "Predictors of Classroom Anxiety in General English (ENT) classes at FPT University"
                        },
                        new
                        {
                            Id = 3,
                            Created_By = new Guid("aaaaaaa2-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Deadline_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "HomePlus - Cổng dịch vụ sống thông minh cho cư dân",
                            Is_Group_Required = true,
                            Major = "Kỹ Thuật Phần Mềm",
                            Semester_Id = 1,
                            Title = "HomePlus- Smart Living Services Portal for Apartment Residents"
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Suspended")
                        .HasColumnType("bit");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Suspended_Until")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Created_At = new DateTime(2025, 12, 10, 5, 54, 17, 167, DateTimeKind.Utc).AddTicks(6148),
                            Email = "admin@fpt.edu.vn",
                            Full_Name = "Administrator",
                            Is_Suspended = false,
                            Major = "System Administrator",
                            Password_Hash = "1",
                            Role = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Created_At = new DateTime(2025, 12, 10, 5, 54, 17, 167, DateTimeKind.Utc).AddTicks(6152),
                            Email = "anh@fpt.edu.vn",
                            Full_Name = "Nguyen Van Anh",
                            Is_Suspended = false,
                            Major = "Ngôn Ngữ Anh",
                            Password_Hash = "1",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Created_At = new DateTime(2025, 12, 10, 5, 54, 17, 167, DateTimeKind.Utc).AddTicks(6155),
                            Email = "bao@fpt.edu.vn",
                            Full_Name = "Nguyen Van Bao",
                            Is_Suspended = false,
                            Major = "Ngôn Ngữ Anh",
                            Password_Hash = "1",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Created_At = new DateTime(2025, 12, 10, 5, 54, 17, 167, DateTimeKind.Utc).AddTicks(6157),
                            Email = "cam@fpt.edu.vn",
                            Full_Name = "Le Thi Cam",
                            Is_Suspended = false,
                            Major = "Quản Trị Kinh Doanh",
                            Password_Hash = "1",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Created_At = new DateTime(2025, 12, 10, 5, 54, 17, 167, DateTimeKind.Utc).AddTicks(6159),
                            Email = "duc@fpt.edu.vn",
                            Full_Name = "Tran Minh Duc",
                            Is_Suspended = false,
                            Major = "Quản Trị Kinh Doanh",
                            Password_Hash = "1",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Created_At = new DateTime(2025, 12, 10, 5, 54, 17, 167, DateTimeKind.Utc).AddTicks(6162),
                            Email = "huy@fpt.edu.vn",
                            Full_Name = "Pham Quoc Huy",
                            Is_Suspended = false,
                            Major = "Kỹ Thuật Phần Mềm",
                            Password_Hash = "1",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Created_At = new DateTime(2025, 12, 10, 5, 54, 17, 167, DateTimeKind.Utc).AddTicks(6165),
                            Email = "khanh@fpt.edu.vn",
                            Full_Name = "Vo Thi Khanh",
                            Is_Suspended = false,
                            Major = "Kỹ Thuật Phần Mềm",
                            Password_Hash = "1",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Created_At = new DateTime(2025, 12, 10, 5, 54, 17, 167, DateTimeKind.Utc).AddTicks(6167),
                            Email = "lam@fpt.edu.vn",
                            Full_Name = "Nguyen Hoang Lam",
                            Is_Suspended = false,
                            Major = "Kỹ Thuật Phần Mềm",
                            Password_Hash = "1",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Created_At = new DateTime(2025, 12, 10, 5, 54, 17, 167, DateTimeKind.Utc).AddTicks(6169),
                            Email = "my@fpt.edu.vn",
                            Full_Name = "Tran Thi My",
                            Is_Suspended = false,
                            Major = "Kỹ Thuật Phần Mềm",
                            Password_Hash = "1",
                            Role = "Student"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Created_At = new DateTime(2025, 12, 10, 5, 54, 17, 167, DateTimeKind.Utc).AddTicks(6171),
                            Email = "son.instructor@fpt.edu.vn",
                            Full_Name = "Pham Thanh Son",
                            Is_Suspended = false,
                            Major = "Teacher",
                            Password_Hash = "1",
                            Role = "Instructor"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa2-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Created_At = new DateTime(2025, 12, 10, 5, 54, 17, 167, DateTimeKind.Utc).AddTicks(6173),
                            Email = "ha.instructor@fpt.edu.vn",
                            Full_Name = "Le Thi Ha",
                            Is_Suspended = false,
                            Major = "Teacher",
                            Password_Hash = "1",
                            Role = "Instructor"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbb1-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            Created_At = new DateTime(2025, 12, 10, 5, 54, 17, 167, DateTimeKind.Utc).AddTicks(6204),
                            Email = "tri.committee@fpt.edu.vn",
                            Full_Name = "Nguyen Minh Tri",
                            Is_Suspended = false,
                            Major = "Teacher",
                            Password_Hash = "1",
                            Role = "GraduationProjectEvaluationCommitteeMember"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbb2-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            Created_At = new DateTime(2025, 12, 10, 5, 54, 17, 167, DateTimeKind.Utc).AddTicks(6206),
                            Email = "thu.committee@fpt.edu.vn",
                            Full_Name = "Tran Hoai Thu",
                            Is_Suspended = false,
                            Major = "Teacher",
                            Password_Hash = "1",
                            Role = "GraduationProjectEvaluationCommitteeMember"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbb3-bbbb-bbbb-bbbb-bbbbbbbbbbb3"),
                            Created_At = new DateTime(2025, 12, 10, 5, 54, 17, 167, DateTimeKind.Utc).AddTicks(6209),
                            Email = "duy.committee@fpt.edu.vn",
                            Full_Name = "Vo Quoc Duy",
                            Is_Suspended = false,
                            Major = "Teacher",
                            Password_Hash = "1",
                            Role = "GraduationProjectEvaluationCommitteeMember"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbb4-bbbb-bbbb-bbbb-bbbbbbbbbbb4"),
                            Created_At = new DateTime(2025, 12, 10, 5, 54, 17, 167, DateTimeKind.Utc).AddTicks(6211),
                            Email = "yen.committee@fpt.edu.vn",
                            Full_Name = "Pham Thi Yen",
                            Is_Suspended = false,
                            Major = "Teacher",
                            Password_Hash = "1",
                            Role = "GraduationProjectEvaluationCommitteeMember"
                        });
                });

            modelBuilder.Entity("BusinessObject.Models.DashboardCache", b =>
                {
                    b.HasOne("BusinessObject.Models.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("Semester_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("BusinessObject.Models.ReviewLog", b =>
                {
                    b.HasOne("BusinessObject.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("Reviewer_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObject.Models.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("Submission_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("BusinessObject.Models.StudentGroup", b =>
                {
                    b.HasOne("BusinessObject.Models.User", "Creator")
                        .WithMany("CreatedGroups")
                        .HasForeignKey("Created_By")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObject.Models.Topic", "Topic")
                        .WithMany("Groups")
                        .HasForeignKey("Topic_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("BusinessObject.Models.StudentGroupMember", b =>
                {
                    b.HasOne("BusinessObject.Models.StudentGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("Group_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObject.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BusinessObject.Models.Submission", b =>
                {
                    b.HasOne("BusinessObject.Models.StudentGroup", "Group")
                        .WithMany()
                        .HasForeignKey("Group_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObject.Models.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("Semester_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObject.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("Topic_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Semester");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("BusinessObject.Models.SubmissionFile", b =>
                {
                    b.HasOne("BusinessObject.Models.Submission", "Submission")
                        .WithMany("Files")
                        .HasForeignKey("Submission_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("BusinessObject.Models.SuspensionRecord", b =>
                {
                    b.HasOne("BusinessObject.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObject.Models.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("Submission_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("BusinessObject.Models.ThesisModeration", b =>
                {
                    b.HasOne("BusinessObject.Models.Submission", "Submission")
                        .WithOne("Moderation")
                        .HasForeignKey("BusinessObject.Models.ThesisModeration", "Submission_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("BusinessObject.Models.Topic", b =>
                {
                    b.HasOne("BusinessObject.Models.User", "Creator")
                        .WithMany("Topics")
                        .HasForeignKey("Created_By")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObject.Models.Semester", "Semester")
                        .WithMany("Topics")
                        .HasForeignKey("Semester_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("BusinessObject.Models.Semester", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("BusinessObject.Models.StudentGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("BusinessObject.Models.Submission", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Moderation")
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessObject.Models.Topic", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("BusinessObject.Models.User", b =>
                {
                    b.Navigation("CreatedGroups");

                    b.Navigation("Topics");
                });
#pragma warning restore 612, 618
        }
    }
}
