// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.DashboardCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Approved_Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("Generated_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Plagiarism_Count")
                        .HasColumnType("int");

                    b.Property<int>("Reject_Count")
                        .HasColumnType("int");

                    b.Property<int>("Semester_Id")
                        .HasColumnType("int");

                    b.Property<int>("Submitted_Count")
                        .HasColumnType("int");

                    b.Property<int>("Total_Students")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Semester_Id");

                    b.ToTable("DashboardCaches");
                });

            modelBuilder.Entity("BusinessObject.ReviewLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("New_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Original_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Reviewer_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Submission_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Reviewer_Id");

                    b.HasIndex("Submission_Id");

                    b.ToTable("ReviewLogs");
                });

            modelBuilder.Entity("BusinessObject.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("BusinessObject.StudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Created_By")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Topic_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Created_By");

                    b.HasIndex("Topic_Id");

                    b.ToTable("StudentGroups");
                });

            modelBuilder.Entity("BusinessObject.StudentGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Group_Id")
                        .HasColumnType("int");

                    b.Property<bool>("Is_Leader")
                        .HasColumnType("bit");

                    b.Property<Guid>("Student_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Group_Id");

                    b.HasIndex("Student_Id");

                    b.ToTable("StudentGroupMembers");
                });

            modelBuilder.Entity("BusinessObject.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Group_Id")
                        .HasColumnType("int");

                    b.Property<bool>("Plagiarism_Flag")
                        .HasColumnType("bit");

                    b.Property<float>("Plagiarism_Score")
                        .HasColumnType("real");

                    b.Property<string>("Reject_Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Reviewed_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Semester_Id")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Submitted_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Topic_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Group_Id");

                    b.HasIndex("Semester_Id");

                    b.HasIndex("Topic_Id");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("BusinessObject.SubmissionFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("File_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("File_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firebase_Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Submission_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Uploaded_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Submission_Id");

                    b.ToTable("SubmissionFiles");
                });

            modelBuilder.Entity("BusinessObject.SuspensionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved_By_Gpec")
                        .HasColumnType("bit");

                    b.Property<bool>("Approved_By_Sdc")
                        .HasColumnType("bit");

                    b.Property<bool>("Detected_By_Ai")
                        .HasColumnType("bit");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Student_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Submission_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Student_Id");

                    b.HasIndex("Submission_Id");

                    b.ToTable("SuspensionRecords");
                });

            modelBuilder.Entity("BusinessObject.ThesisModeration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Academic_Rigor_Pass")
                        .HasColumnType("bit");

                    b.Property<bool>("Citation_Quality_Pass")
                        .HasColumnType("bit");

                    b.Property<bool>("Completeness_Pass")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ethical_Compliance_Pass")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Approved")
                        .HasColumnType("bit");

                    b.Property<bool>("Originality_Pass")
                        .HasColumnType("bit");

                    b.Property<bool>("Plagiarism_Pass")
                        .HasColumnType("bit");

                    b.Property<float>("Plagiarism_Score")
                        .HasColumnType("real");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Research_Relevance_Pass")
                        .HasColumnType("bit");

                    b.Property<int>("Submission_Id")
                        .HasColumnType("int");

                    b.Property<string>("Violations_Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Writing_Quality_Pass")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Submission_Id")
                        .IsUnique();

                    b.ToTable("ThesisModerations");
                });

            modelBuilder.Entity("BusinessObject.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Created_By")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deadline_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Group_Required")
                        .HasColumnType("bit");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Semester_Id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Created_By");

                    b.HasIndex("Semester_Id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("BusinessObject.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Suspended")
                        .HasColumnType("bit");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Suspended_Until")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusinessObject.DashboardCache", b =>
                {
                    b.HasOne("BusinessObject.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("Semester_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("BusinessObject.ReviewLog", b =>
                {
                    b.HasOne("BusinessObject.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("Reviewer_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObject.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("Submission_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("BusinessObject.StudentGroup", b =>
                {
                    b.HasOne("BusinessObject.User", "Creator")
                        .WithMany("CreatedGroups")
                        .HasForeignKey("Created_By")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObject.Topic", "Topic")
                        .WithMany("Groups")
                        .HasForeignKey("Topic_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("BusinessObject.StudentGroupMember", b =>
                {
                    b.HasOne("BusinessObject.StudentGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("Group_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObject.User", "Student")
                        .WithMany()
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BusinessObject.Submission", b =>
                {
                    b.HasOne("BusinessObject.StudentGroup", "Group")
                        .WithMany()
                        .HasForeignKey("Group_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObject.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("Semester_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObject.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("Topic_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Semester");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("BusinessObject.SubmissionFile", b =>
                {
                    b.HasOne("BusinessObject.Submission", "Submission")
                        .WithMany("Files")
                        .HasForeignKey("Submission_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("BusinessObject.SuspensionRecord", b =>
                {
                    b.HasOne("BusinessObject.User", "Student")
                        .WithMany()
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObject.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("Submission_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("BusinessObject.ThesisModeration", b =>
                {
                    b.HasOne("BusinessObject.Submission", "Submission")
                        .WithOne("Moderation")
                        .HasForeignKey("BusinessObject.ThesisModeration", "Submission_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("BusinessObject.Topic", b =>
                {
                    b.HasOne("BusinessObject.User", "Creator")
                        .WithMany("Topics")
                        .HasForeignKey("Created_By")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObject.Semester", "Semester")
                        .WithMany("Topics")
                        .HasForeignKey("Semester_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("BusinessObject.Semester", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("BusinessObject.StudentGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("BusinessObject.Submission", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Moderation")
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessObject.Topic", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("BusinessObject.User", b =>
                {
                    b.Navigation("CreatedGroups");

                    b.Navigation("Topics");
                });
#pragma warning restore 612, 618
        }
    }
}
